name: vehicle_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  iconly: ^1.0.1
  provider: ^6.0.5
  dio: ^5.3.2
  flutter_hooks: ^0.20.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
     - asset/images/
  fonts:
     - family: main
       fonts:
         - asset: asset/font/MetrikTrial-Medium.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
